language: cpp
cache: apt
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libtool autotools-dev autoconf libssl-dev pkg-config
  - sudo apt-get install libboost1.48-dev libboost-chrono1.48-dev libboost-filesystem1.48-dev libboost-program-options1.48-dev libboost-system1.48-dev libboost-test1.48-dev libboost-thread1.48-dev
  - sudo apt-get install libdb++-dev
  - sudo apt-get install libqt4-dev 
  - sudo apt-get install  libprotobuf-dev protobuf-compiler
script:
  - ./autogen.sh
  - ./configure CFLAGS="-O3"
  - make -j 2
after_install:
  - cd /home/travis/build/dogecoin/dogecoin/
  - for t in `grep -r TEST_SUITE\( ./src/test/*.cpp |sed "s/^.*(//;s/[,)].*$//"`; do ./src/test/test_dogecoin --run_test=$t; done
notifications:
  irc:
    channels:
      - "chat.freenode.net#dogecoin-dev"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
